---
- name: CREATING A BACKUP FOR ROUTER1
  hosts: Router1
  gather_facts: false
  connection: local
 
  tasks:
   - name: SHOWING THE STARTUP RUNNING CONFIGURATION
     ios_command:
       commands:
         - show startup-config
     register: startupconfig
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ startupconfig.stdout[0] }}"
       dest: "backups/backup_Router1_startup.txt"

   - name: SHOWING THE RUNNING CONFIGURATION
     ios_command:
       commands:
         - show running-config
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/backup_Router1.txt"